# -*- coding: utf-8 -*-

"""
Report Generator
Generates TXT and JSON reports.
"""

import os
import json
import datetime
import platform


REPORT_HEADER = """
===========================================================================
LINUX PRIVILEGE ESCALATION AUDIT REPORT
===========================================================================

Generated by Linux PrivEsc Automation Toolkit

Report generated : {timestamp}
Hostname         : {hostname}
Kernel           : {kernel}
Analyst          : {analyst}
Duration         : {elapsed} seconds

===========================================================================
"""


class ReportGenerator:

    def __init__(self, findings, start_time, elapsed):
        self.findings = findings
        self.start_time = start_time
        self.elapsed = elapsed

    def total_findings(self):
        count = 0

        for module_data in self.findings.values():
            if isinstance(module_data, dict):
                for value in module_data.values():
                    if isinstance(value, list):
                        count += len(value)

        return count

    def _get_system_info(self):

        sysinfo = self.findings.get("System Information", {})

        return {
            "hostname": sysinfo.get("hostname", platform.node()),
            "kernel": sysinfo.get("kernel", platform.release()),
            "analyst": sysinfo.get(
                "whoami",
                os.environ.get("USERNAME", "unknown")
            )
        }

    def _section(self, title):

        return (
            "\n"
            + "=" * 75
            + "\n"
            + title
            + "\n"
            + "=" * 75
            + "\n"
        )

    def _format_system_info(self):

        data = self.findings.get("System Information", {})

        if not data:
            return "No data collected.\n"

        output = []

        output.append(f"Hostname : {data.get('hostname', 'N/A')}")
        output.append(f"OS       : {data.get('os_name', 'N/A')}")
        output.append(f"Kernel   : {data.get('kernel', 'N/A')}")
        output.append(f"Arch     : {data.get('arch', 'N/A')}")
        output.append(f"User     : {data.get('id', 'N/A')}")
        output.append(f"Home Dir : {data.get('home', 'N/A')}")

        writable = data.get("writable_path_dirs", [])

        if writable:
            output.append("")
            output.append("Writable PATH Directories:")

            for p in writable:
                output.append(f"  - {p}")

        return "\n".join(output)

    def _format_suid(self):

        data = self.findings.get("SUID/SGID Binaries", {})

        if not data:
            return "No SUID information available.\n"

        output = []

        output.append(
            f"Total SUID binaries : {len(data.get('suid_binaries', []))}"
        )

        output.append(
            f"Total SGID binaries : {len(data.get('sgid_binaries', []))}"
        )

        output.append(
            f"Exploitable SUIDs   : {len(data.get('exploitable_suid', []))}"
        )

        exploitable = data.get("exploitable_suid", [])

        if exploitable:

            output.append("")
            output.append("Potentially Exploitable SUID Binaries:")

            for item in exploitable:

                output.append(
                    f"  Binary : {item.get('path', '')}"
                )

                output.append(
                    f"  Method : {item.get('exploit', '')}"
                )

                output.append("")

        return "\n".join(output)

    def _format_permissions(self):

        data = self.findings.get("File Permissions", {})

        if not data:
            return "No permission data available.\n"

        output = []

        output.append(
            f"World Writable Files : {len(data.get('world_writable_files', []))}"
        )

        output.append(
            f"World Writable Dirs  : {len(data.get('world_writable_dirs', []))}"
        )

        if data.get("passwd_writable"):
            output.append("")
            output.append("[CRITICAL] /etc/passwd is writable")

        if data.get("shadow_readable"):
            output.append("")
            output.append("[CRITICAL] /etc/shadow is readable")

        return "\n".join(output)

    def _format_services(self):

        data = self.findings.get("Misconfigured Services", {})

        if not data:
            return "No service data available.\n"

        output = []

        service_issues = data.get("service_issues", [])

        output.append(
            f"Service Issues Found : {len(service_issues)}"
        )

        for issue in service_issues:

            output.append("")
            output.append(
                f"Severity : {issue.get('severity', 'UNKNOWN')}"
            )

            output.append(
                f"File     : {issue.get('file', '')}"
            )

            output.append(
                f"Reason   : {issue.get('reason', '')}"
            )

        sudo_issues = data.get("sudo_issues", [])

        if sudo_issues:

            output.append("")
            output.append("Dangerous Sudo Rules:")

            for issue in sudo_issues:

                output.append(
                    f"  [{issue.get('severity')}] "
                    f"{issue.get('description')}"
                )

        return "\n".join(output)

    def _format_cron(self):

        data = self.findings.get("Cron Job Analysis", {})

        if not data:
            return "No cron data available.\n"

        output = []

        output.append(
            f"Cron Entries : {len(data.get('entries', []))}"
        )

        vulns = data.get("vulnerabilities", [])

        output.append(
            f"Vulnerabilities : {len(vulns)}"
        )

        for vuln in vulns:

            output.append("")
            output.append(
                f"[{vuln.get('severity')}] "
                f"{vuln.get('type')}"
            )

            output.append(
                vuln.get("detail", "")
            )

        return "\n".join(output)

    def _format_kernel(self):

        data = self.findings.get("Kernel CVE Detection", {})

        if not data:
            return "No kernel data available.\n"

        output = []

        output.append(
            f"Kernel Version : {data.get('kernel_version', 'N/A')}"
        )

        output.append(
            f"CVE Matches    : {len(data.get('vulnerable_cves', []))}"
        )

        for cve in data.get("vulnerable_cves", []):

            output.append("")
            output.append(
                f"{cve.get('cve')} - {cve.get('name')}"
            )

            output.append(
                f"Severity : {cve.get('severity')}"
            )

        return "\n".join(output)

    def _mitigation_section(self):

        return """
1. Remove unnecessary SUID binaries.

2. Audit sudoers configuration.

3. Restrict world-writable files.

4. Review cron jobs running as root.

5. Harden systemd service files.

6. Patch vulnerable kernels regularly.

7. Enable AppArmor or SELinux.

8. Follow CIS Linux Benchmarks.
"""

    def export_txt(self, output_path):

        sysinfo = self._get_system_info()

        report = REPORT_HEADER.format(
            timestamp=self.start_time.strftime(
                "%Y-%m-%d %H:%M:%S"
            ),
            hostname=sysinfo["hostname"],
            kernel=sysinfo["kernel"],
            analyst=sysinfo["analyst"],
            elapsed=self.elapsed
        )

        report += self._section("1. SYSTEM INFORMATION")
        report += self._format_system_info()

        report += self._section("2. SUID / SGID ANALYSIS")
        report += self._format_suid()

        report += self._section("3. FILE PERMISSIONS")
        report += self._format_permissions()

        report += self._section("4. SERVICES")
        report += self._format_services()

        report += self._section("5. CRON JOBS")
        report += self._format_cron()

        report += self._section("6. KERNEL ANALYSIS")
        report += self._format_kernel()

        report += self._section("7. MITIGATION")
        report += self._mitigation_section()

        report += "\n\nEND OF REPORT\n"

        report_dir = os.path.dirname(output_path)

        if report_dir:
            os.makedirs(report_dir, exist_ok=True)

        with open(
            output_path,
            "w",
            encoding="utf-8"
        ) as f:
            f.write(report)

    def export_json(self, output_path):

        report_dir = os.path.dirname(output_path)

        if report_dir:
            os.makedirs(report_dir, exist_ok=True)

        output = {
            "metadata": {
                "tool": "Linux PrivEsc Automation Toolkit",
                "timestamp": self.start_time.isoformat(),
                "duration_seconds": self.elapsed,
                "total_findings": self.total_findings()
            },
            "findings": self.findings
        }

        with open(
            output_path,
            "w",
            encoding="utf-8"
        ) as f:
            json.dump(
                output,
                f,
                indent=4,
                ensure_ascii=False,
                default=str
            )